apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:MeBYI22+GWDycJwq4kqlDvLspitK89NT9LuFw5v1zVFmA0j0d958q7qJW7P+ghTdqVL8vgj3Yp13/rAxw62TKQlRW93ajuVP69a7M/5A0LCizUlbZ5uVyFK68WsJuT10rdplbOikWJYd2whtQiisPbP/Oa/xiRxW56dAZdG6aU3JFph1G1A1bBl1lVwl75vD7IfCt4hYAivxwXgBBKIwaUn48lAFlrQec19Tf0J9rNSeJSX/h6256TskxzcsIX6tNCblDqbX+o/knI+UluOmHEUfW8P8QOwgmDUZE5lTtRz2HTgn/Ach7ANuIdQ=,iv:JL5XEEKL4mFbD2SOzXpgnWuGXVIp2CBZbo0d/VhAjss=,tag:SzPFROSiAwaA7hbjgeeecA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZUZXN1hBaThBeUtpOFZH
            WmRFRDlnSzgxanBGU1Z3QzBkYm0reGs3aldRClcrUDc5T0xXUmk3c2tRZENPd0dm
            UGNVOU5zL2NsS1h0aEZpZVllQ3kxbncKLS0tIHkwd0xkeHFNc0xzd3dXaWU4dXFN
            UU5qck92eUZVaVVsRjJWRnJqMW9DMDAKwm+XjVhc7vLTheaU6NhvmTJXL6nPkyCX
            eEpTL/zsfTIPujt0EDCawakdtvnJni7AqtwNEnvuMXdgKKhoW/8bCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T00:38:57Z"
    mac: ENC[AES256_GCM,data:PPxawkgQNhSUtwf4xyuygbV0poQ/tTbX57zsRVbobtB3w4vmL9/pqQlqaVU0Te91n6ILmXC0ZZI2aV82uc/tzKiTxaB4KebdR8Lq9Znj+yUPec7VuGu7ZlN0+V5Yput8ou05tOmGQQWilnwVqErGBUabkBckkIT2LRZZdI9XRX0=,iv:iNvuvhJ7aaZPclwkH9UzxckFnexqrwqyUeuPAF2bU0c=,tag:IbzTXzR09LU9b1Ezllisbw==,type:str]
    version: 3.13.3
