apiVersion: v1
data:
    HOMEPAGE_ALLOWED_HOSTS: ENC[AES256_GCM,data:M8RUYZdD7UV/7wtZ+XypxYNKzuE6dm/+bNpyxZT+7o61ExEH,iv:T7Etj4Nns2z7wKQnJuAYM+yWn/LG6MkhDM9C/HrdDr8=,tag:fB8vaSqtNpWaY4EICh8xtA==,type:str]
    HOMEPAGE_AUTH_ENABLED: ENC[AES256_GCM,data:gwe1OtCV36s=,iv:/TYtbN/syCY3zxj9U9xIEheBCRVGBx2cw7d4EYjsk+Y=,tag:7rTmIO6i9iQvb2dsEzvLPQ==,type:str]
    HOMEPAGE_AUTH_PASSWORD: ENC[AES256_GCM,data:pd2Ca9VMenF24ok/PTzNcQ==,iv:B08WIy1wYdk3Nx1EioliUbz+JgUgSD9PC6RrrMBu/MA=,tag:jypr3PmsiFDhPpALPsAA7w==,type:str]
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:PdCP6yo2JAZEZQsUOS/r8GTIlfHlxkZANEuRKNKN8MgSwsVFUsWc16vWnC1noDgJRb0aDUbyxsfaNEQ6,iv:p9yc1QoZjUNeA3y69U1Qv3VZwdq8TZL6tpsgS1c8k2Y=,tag:/vQxr9XPH0QVOcMlgxAXmg==,type:str]
    HOMEPAGE_EXTERNAL_URL: ENC[AES256_GCM,data:GO8gZcQdYP4WJ+D7ylNrsV3W26awqUIsr8nYD9KTUHGWp5MLBo8NuXUHz6hL1ekx,iv:jdnPnaLn7jXXMdRegof+VBBnIcV+wfwcfXI5jzGdIb4=,tag:ivf7AMx/FAnMTOeSNSilxg==,type:str]
kind: Secret
metadata:
    name: homepage-auth
    namespace: homepage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb2ZlcTVyZnY0WGJEWFlB
            cW5FamxQTVdOeGs2VExSNitIbmY1aGVza2kwCkFUTTUxZDJwWU5pT2lLUFh5M3g1
            MjYrSkdwaktqOU9xYzcxOGRFbFJaZ2MKLS0tIGo4NWt3NitwWEZPMjhnbTdqcG5T
            WDlTVWIxOGt2UkM3NXA2WUl3d21sYkEKGBMXdmXBuCRH5Ysqw0OQbg3iRa04VpGK
            Y4Mcz0cYlYMdQf/vcj9GduZ2QvLy8+FcdEl/uaUZiMw0lMIe+vov+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T03:51:19Z"
    mac: ENC[AES256_GCM,data:r4TGVGCCx4DlfBIy40zwj3W5Et+vfSCYe7vxIieEVMicYXHRt+jfwaXkVLsl3r2KnpwaEa8EfKPLQXEjG0r3np8W52RY9A2QV8Cfs7xAh4po/Snw9G7h6UzRVKXY4Wu30Hz2P3pu+Uk1VgwYedNYwKNIbBNeFvN2JHL8ZNna67E=,iv:T8T+Op2Lou4FW7hZoXTcnv4OQK5XU29rm1mQMQTuIPY=,tag:KuFfKngtfVg4QNh8k3k7Zw==,type:str]
    version: 3.13.3
