apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:S8sL+sa8qPuESbG1bAkY1OaBydVorILqdq3WeiIp3G7CCnwbW/Q+/0EFi73gkzZ3vSlnz/FXU/eQHbBJS/FdTp3oMFbsUUdzNjSm2iZnupPjgwC9KHaZvxgAVphutx4RYceWEQxwqWtgSNhvZ4pIF/wV0J4i+9s3XCaZCHfdf4vyTM3H/Vp4K20aSoiIWzr7ySk1Yv4ajRYL/Rbm86oOAtY1zN11eq1I8j0HI3DIieMr5tPRgpSy6aPVMhUZGVSALU2rtDsGke4wkAFshpq6dN80QzO45U946SULXlZqxoxWFE/n55YhtSofiiI=,iv:EYQ2ackdLNYR24vWb13K4mSz3xUMgRcaOw9Bk8ErI8U=,tag:uAhnEkj34lpzsImW83KEKg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcEFEVkZjVGY3UlpRdFRR
            MHdkVVc1Uk9EdXgrYlZKcVg3WWdOaEx1MHpzCjdWQnN3Mk9RbzM5dWxxamVacVNh
            eGRtczRjQ0NZZXZBSHpEUnlpQTcrcEEKLS0tIFRGNGZtTWRGcHROZ3dTMGdONERZ
            aWd0bFh1V0gxYzE2NDlBY0pmVHFoNE0K/DAelfejeXDTd9bO5Av2RqMRNDSqn/A8
            vK7Yjq0Hsqga1poh1E0yMSUbynpzIX0p3tZqo4JtQ/XkrK6Sb23lEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T02:15:52Z"
    mac: ENC[AES256_GCM,data:0itUybrFP3ZJtQmSJivcOWu5r4FwtAvkwp8Wv2ZmahbHrD8Y1sBJJFb8EagGdO8jsq8km2eqgpK25By2nKPN4k7munHYzSGPQGOLxjAQjsiaeLMikqrr1M1VwL9vfn8d6O0Z4QMrC0WWosMgDeLiUot6qj716P1Z5kb6y5d0HZQ=,iv:JKjL16PxjEwTeiVrdUGha05ozZSsWGuenuOUSZVAFj0=,tag:ZY/r6mqw5A78Wi7zsqc86Q==,type:str]
    version: 3.13.3
