apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TSezmDq/HRL1L5a9jrqAWQ==,iv:7vESpAikJh+fAe7taWJPvMIDHlfsql4VhksPB6cRdq8=,tag:no6ZuZBcOFfunB/YqwpLsQ==,type:str]
    username: ENC[AES256_GCM,data:gWx5LQ==,iv:dC/FIFiV+l3JJ/AJB/C1Nh5M9GCh82RLQWjZvFEVRes=,tag:XjxYPbdV22PS7Gx8IgLduA==,type:str]
kind: Secret
metadata:
    name: n8n-postgres-creds
    namespace: n8n
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY1lPY1FFaW90R1d5Uk4y
            V25FaG1ER3VvK3VTRFBDZ0VzV0l4dCtpMTJvCnlDc3ZqZzZEV2M1MVRxSithQzFj
            aHgzbXBGRzYvTGRDVUU3aTRkM3RJKzgKLS0tIGlhMjBLYlVLelZQZ1JVVmx2Wjhi
            bVpsNVczSTYxcWxjR1lrK0ZSSkhVYzAKmkiFZJ8bGXqzE1hfl5gz7yHgDpSa9DNw
            7/BiyZER/tPHLiQgCWY8RSwnNkt8a7PDvygepNgEGQwFaOL/LVDMlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T03:52:22Z"
    mac: ENC[AES256_GCM,data:a/RWgI5biIsYKVZVUs1NY7qTDYgyPLynNQ+jzK/fX81pRnjGdGsogP8YknjLKk34tOBTsm1wmZpYfIBIt4bns3wqdCWMPk3PV784G4TETiBr4nOSVhXT5zGuZgAFNDzLxc37m0IXbaPVKKGU3Prm1tpXvU9tC6CMi4O+8rxCWiI=,iv:FZbB/pPp0L30nnjTKrU+yIZFzId51yI/4vvfcXY/z5c=,tag:SzfKO8ZhKc+ffSvyIPgt6A==,type:str]
    version: 3.13.3
