apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:G27ILJGkzrsjBmcIoQGFdNnZJYZneA7d0dJOvqwKuOEVZlvw0uASSLZDtqD8ztG7470uSlG6+pF6QY/SZifcwoGWSGiBmCeEeTu0XAj9/ulBWZ2+z198xReHbw5kwYFBE+MqA4/UWveFQ4JhYgeCl3AqZaQKK6bjICXV73suFTjRXOj9SXEja7tROoDIxy6fOgzOIdQrGD2ZBROMA0YknZvHNwaRFTD+qj1cqcRiPPJebBsNvV/qGOHTRkNQ4BQ+amkYx/YJLtMGWakRSY2jIEY+KP78nbnYXT5dy6RB/u1maajjyz6h5pFSRFE=,iv:RMW4ZUvTk3Tbhc9xVUXpWjC/Zn8l1un+bW2RhHxg4dk=,tag:fbsZLVCl+nak+QfemiHIFA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOG5QSlplZEpXQWExWUIr
            MDhOcUx2SFZjQStDQmJ0MHB6dlBBdjVZczNvCm8xd1R6d2hPQUlsS0ZMYnhsUHR2
            eVViUEhEQ2hjT3dXN0RnV0VUSWRkdncKLS0tIFRicHBGOFFwcjdhWXpyVkRYSDFJ
            NXVUV240aWVYMWg0N0VKVEE0blUxN3MKABk+ExaZB8QDA+B4YUImj5Oajh0I6TX6
            YfkHchbfZ09vFmrB+KgSA3q5uSomSFysU+bqx000ur9a9CrCFs5iTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T18:27:47Z"
    mac: ENC[AES256_GCM,data:iN9CmBzJsiOtiACTr6hQGj11Eh+gSs8nRUEYwtNrG4b9jB7hkzhWVLtAkpJ2JMZ+NWT/ugK47b76+lvieoEScju5/pBwOetimskjpwn39U7O7gMz5CuFzEGhZNy4BFKOLxqdi1eM+5q76gZZqrn3tkLkF66rrcJF0ExvKHUHYAI=,iv:gfG6WkmfcJOMOqTTvbFEpS8eleVw8uY2dWsaJ8p6fiQ=,tag:ZS1Ugbzthduye/K4aQdjDA==,type:str]
    version: 3.13.3
