apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:EymsUZ7eZg+anH7h0PjLAXqt5nklV8YWSu9DW5dSwEq8+YNJof/jKFmMSA3+M1qfaA5+H+9ce6Mqmst/+x/RlThTXzH7e/mIGI1YYR3Dm6Ci6Hff/H6/kuRFCaGuzGVWKtMTgQzSLfnuPxmArqBkfH+KE1hEN5dD4PaBPGBoU3zTcxuQymay+T269zPg33VkOF1tCfesn3rC1Ntu9htPA52E+p/dN2o8Ptdy5iqAYXHOVMpovZEQhvacJNm7ph6y7s6I3cBLFuFPHYNdy4yqVB5tN1j/3MyYv2MdRkdc1Nn80i4kfntvr9Cpg5o=,iv:fif5hinanrEowG/tUQ3QFBpT7opGqvPAAkrW+9jQaDY=,tag:KyaiMc0lJpeEXT6pDBpCiw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUkhTNW9oOFFwRmxuRHpZ
            ZE5SenJ2N3ROT0M4TURXM1ZLMWMwejlIYWljCml5bmJRNWk0N2ZDMnJRUmJsOHJ4
            Z1NvQjZGTmdJWWtqbUU4bmVGa1JEclkKLS0tIHpWdktPeENrSm1Nb2N6TWwxUDNs
            OUVTMHI1OUxGZUEvQzNOVUFVWnZiUFkKW+v3qk6lBixXtzDZ/S2eOS3hKsTmlS6V
            L6yzFAX7+nzsdzjSazjftsZbzro4SpIy1Mpl7r2/PnxfJMjbyiMNFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T00:42:19Z"
    mac: ENC[AES256_GCM,data:HlrNdWmRTLUbZikEjj0ItH1aVF79A4ANjUp3mtc7QGQ+Ino/VUmFN2NL0iqR3Ek5SqAO5iaPyErUGcs39/UoXqx1N/fFQNVUfh6pvJLeZMVYSG5SDtbfVGoPLaULDECsdhZrwVH+deoAq8ktp1dFl2gz12Yu78ohCzldDTYotSQ=,iv:9DOPTwlEg9Ypm8xKhMdhODg0pHYo31DzLkQgJ+KtoTA=,tag:+OrjLtuJ9h+wUR0XZ7Gfug==,type:str]
    version: 3.13.3
