apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:mdyv9EIh1LBfwDu45JahyzOJtK0KauFOSLPFsvtbLG0jvxX+c53p0+LivLADbRlY2AjBym/zQub2lpgsO/lPOXdXwGSJ+G0TTsDRPtT4tX6rOpcQ8fjT5T2/baapIwFjQKvSPL6yn7GgkGdd/ht0yhI0sUqZzmTFPmkc757D9VWLFZqf1L6vj9cULrUX0wm9f8YcEDJfvkD8LQcVp6zHXss4uAc2cspHGic7zbIRO+u0jxOO+jtnlXUXDShyMOPDXrZpS/EKqMvzRSzoEV+SQ2fA/wMIizXS0gLKR/NVSrsJycP1owYw3Cu99yU=,iv:Gbg2xSSH9lemzFCvwgxoDL9l5sHj4pXhI7ghbvLaYWo=,tag:SrNTnwQ6OPyE0IlNAY+fCQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTHVsTUFXQWZib095dStw
            UDR0eG9MQWlhZmQ2SVBrcERhWEI0RDVhN1cwCk1qa0Y5cThNdXczY0R4SXEyNU9R
            TzJSdUlFOUgyY2NiUE1McHg1dzNWTVUKLS0tIDRtYVAwbjlrZXh5MUNIVEtaekJi
            NWJKeHpMVXBXOXgyRll1L0ZoMGtGS2cK2+d6bi74ChUSyItkFZFg0L/jNXvkmSsW
            P0/8iqlfPVAkLUFYGhHSN5O1eBR5mUm5lV0Dy0DqvkEJmANwpESXfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T14:20:05Z"
    mac: ENC[AES256_GCM,data:UbiT5TXRv6jCYX2GRY2oFOr8CKKA8Xz3Oi4oX4ycxn7Sp6/1MClGQI0EXN0GfNbqzEPyGNb7MeX67Q36+vsXyCuBi3Ealm1xPX/01t2bJwD+a38Z9U68ZRpu3gdIUQxFUZVJcaQ3KuzwD3izr+rzB5x3Ia8zM+yicqI/UplTp1U=,iv:+Sb9zge1GmLl0ubLyYP8KLulfAVXqLn1jjEKQHEh5zU=,tag:01eUqMpdFqnRzpOmpcaHCg==,type:str]
    version: 3.13.3
