apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:4bY3RkivT8RK1zXN,iv:HjBnzzmudmpgvzFDoHSYhvAqZWDXnpWbTVm/I7iwd8o=,tag:7eaS4tEQzDAdBU0/RHns8w==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:+cAiJN+pGrPGJbxGt2hyRQ==,iv:jXzCfTb6c7FJdezMuQ8fVZyHZvjMZwgB67NtF0j/BJg=,tag:xH/KEqe9u7c6g3vEjwHicw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaUVJcURGSGxZcDJlRGZo
            YUNKQXVaK0RNaytjZDlFN2pMdUF5Z1BhVXpRClBZY00rN2R0VkpBVHdaanpFWjhN
            YzMydWxQSU1FL2VzNUpRdVljZkYzazQKLS0tIDVWdmw3Q3lGQ3F6OHN2b2laeHM1
            aWVIdHgzU0RGMTFmWS9GYXAzeC9GdTQKfhgsSTPdcFwl98u20hgKOTKDW0ZHPtrF
            4+InEADIftDvkykSpfG+eTXgMLpGkCHboaWl5/n+tjj5xOm3sQUwqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:02:19Z"
    mac: ENC[AES256_GCM,data:eESGzdOsyzEJAHojYbHRwh3C4xPe4bh/2w3HepQ28/8laJ/triTHRGhoOlyQyt0bI9sD6xvwzIqXjsKH+nMDA7pkEeoqjR83ZmsZRxV+9ui47PpCmeZEiCmIGPQeVy8U1ujUrEwQFMb6IkhPBe8h6ZzLIN8QLbNTjTPJRmghGOw=,iv:n49ID8GzQYuW1BfSCqxGylZ/e4E5q3HXxUkVrrwvG48=,tag:gydQkJ20AIrWnB3DsP91sg==,type:str]
    version: 3.13.3
