apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0yjLf0l36HK0dTg4Q8SW1ZEmVGKhWsXSIRqW/ofh977546JUj3VLy88/tqniKzr7qxJBmOSx4pCV4M/YEJW1u7Wezm57rFyafGJH8tcU8xAavvDVHrNY71oyBuVwlQvLRDAN/9JHWqQwJO4DgTu7MsjNly33RHJC5NanAO0XnyGNJ+JnhexKP5aXNjldNKEJr4LmMuuFEKYInSYsVxinBRy1gjfP/OLJaaKx89X5ceVkSr/tG3oyQJrprao7M5B0kRCnIG+IID8iOb9WgWfgJCndvDufRQAuPX7o6cXdBcyHJUli37+ibKC2MM0=,iv:oBt9y0cYpZxEGF+k1ox1IY4adzE2/WZsLtpies1WjWg=,tag:76mBP94/5ImK9VPQh8O+Nw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNk1XUXpkK25qRlZvSkJw
            U3Z4SC9odjlFSlk1WklOSVZzZHBieGNVdndFCk9CRExHcENQQlo5M2RyZjhpRVFN
            eHJ3NEpTaW5zVFJlL0JDTWFvUWpSakEKLS0tIGgrTjRXeEMxMzlaOWZvZ29vYWZv
            T2drUjBBL3dqVXlXejV5ekJvSFJwUjgK7E70vqdA5iGIAV3ZA9c3YCzdYqRPYdjD
            ZTvybGbSGlKJXowbfnjUxSP02oVNeNScaLSrolAcX+fslduR/0L4NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T00:11:58Z"
    mac: ENC[AES256_GCM,data:ZpdVJZkOg7H81UfiwyiMQ8OftyN5t6+eaj4sx38dEDJ5u9b3lRu5dW4v/scQiFp0kztX4lNkLkJb6H63chlBHsYOh/AT/l0yCWZ2pDN1r/vWcjQxN2IU5/wzcjbtiWIO+LCvDah9LpjC8xr3PeoDfBy5w8BxwwaLsXgDTM+B3FQ=,iv:s2t0wbhRzwBI9ld58RvO3p2izYQuKRDiBQqc0wQcu5I=,tag:0gRgr5kOk0ljOL0BejmZIA==,type:str]
    version: 3.13.3
