apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:4bjHrONuhQAFWRR9LBAq5uFOe8zrocte1i+uIB7O0xqLVoJyNNacBYngKdVCU8lBTlpvsEl3nje61v0JuGhgpGEn0ITLJI5l1smZkQ66z8wyFsJ/eYP0s9KUTwZyX6Isxu7bJ4kWfRDa+rWP0vpCLy4LvLc1k6qs5cTNO9OpsAcj9de6zeCnWZnaxbA+Bd4BcQNazoG4ezFcsQp3ACjWjcH0jRZmymiXL8CSBuKXYPsMrxtUuCcgsg+Mczm0oQxeFaha30y5x8aBQNv+GUsuUvo1xCnFP6RGoxi9yoi7Knx+DdjGRy4vjN07WsI=,iv:E5a73vKZSjLh+2cpHo5lVQ2ykCcepqtCzQ1QaQ6g9Ek=,tag:G6h4f6TWLMxZbVocOI122Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUXNoaFFzYjJReGRSZ1Iz
            TDRzRVhvWm1oaWVpNzJmdjJHdFVkUXJkY1hrClFvbDBNNVFBV1JXSGtmbWFWWTYv
            aWpnV2RBRVB3SGdGMFZPdjByTjAzeGcKLS0tIElMK0V5MDF6dEgyRUNzZGJvbVcz
            MDdqMlZCVk5Xc1lhZDdZTm9KR1VNSmMKcN7SYZDob7cBhp7JlX4DJ1PvB+swwtMs
            2m82+bO7qeoOjXyfdGLtBjXHdtXMuTeVGMaZCRz7RYK5QtI6APWBOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T01:27:50Z"
    mac: ENC[AES256_GCM,data:Pgbxs1Yu6vpoHrUGCdUtn73xX8k+AcDvOIyQ16eiQtAri3VuyS356Acp696lCYHrhbA5vE4WqSMk1h11ztnTmyLGMBxlhRVlbhmB0pdvNqIFCKDxnlOyL8aOEuRnrgp/1iHR77I3PW4qN93iwSryBIELHgwJeik+zwo9oG0ummM=,iv:wre1Durs01BXXrXYSwW/6XRPL7Ou6yu/71tFyXvsvoY=,tag:aixNSNrC0fDBkyWn3GXD6g==,type:str]
    version: 3.13.3
