apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
   interval: 30m
   chart:
     spec:
       chart: homepage
       version: 2.1.0

       sourceRef:
         kind: HelmRepository
         name: homepage
         namespace: homepage
       interval: 12h

   values:
     image:
       tag: v2.1.2

     podLabels:
       app: homepage

     env: []
     envFrom:
       - secretRef:
           name: homepage-auth

     podSecurityContext:
       runAsNonRoot: true
       fsGroup: 1000

     securityContext:
       runAsUser: 1000
       runAsGroup: 1000
       allowPrivilegeEscalation: false
       capabilities:
         drop:
           - ALL

     ingress:
       main:
         enabled: true

         ingressClassName: traefik

         hosts:
           - host: homepage.kennedyhomelab.net
             paths:
               - path: /
                 pathType: Prefix

         tls:
           - secretName: homepage-tls-secret
             hosts:
               - homepage.kennedyhomelab.net

     config:
       services:
         - Infrastructure:
           - Grafana:
               icon: grafana.png
               href: https://grafana.kennedyhomelab.net
           - Unifi:
               icon: unifi.png
               href: https://unifi.ui.com/

         - Apps:
           - Forgejo:
               icon: forgejo.png
               href: https://forgejo.kennedyhomelab.net

           - Linkding:
               icon: linkding.png
               href: https://ldplex.kennedyhomelab.net

         - Create:
           - LinkedIn:
               icon: linkedin.png
               href: https://linkedin.com/in/kennedyshearer
           - X:
               icon: x.png
               href: https://x.com/kennedyashearer
           - Skool:
               href: https://www.skool.com/

         - Consume:
           - YouTube:
               icon: youtube.png
               href: https://youtube.com/
           - Audiobookshelf:
               icon: audiobookshelf.png
               href: https://abs.kennedyhomelab.net

       settingsStrings: |
         title: Homepage
         headerStyle: boxed
         layout:
           Infrastructure:
             style: column
             columns: 1
           Apps:
             style: column
             columns: 1
           Create:
             style: column
             columns: 1
           Consume:
             style: column
             columns: 1
