apiVersion: v1
data:
    email: ENC[AES256_GCM,data:24pzZVO4ecouv6PtZlgQwo1jVmP1exUS,iv:+x6xAxhHgqZooUBE3py7akAx2SfNobECxVtsHxnWdZM=,tag:tT1kVm1Rr7wBCtJmCVu/SA==,type:str]
    password: ENC[AES256_GCM,data:U6k0J1uFmQX+WcWakB0jkcFhRdNbjmI2,iv:6BK60Kw4wWwWuXUITwCPlgh6JZlTrJRZNFN8Fa2V1y4=,tag:p7MivWCEVv7xD3yZ/BIDSw==,type:str]
    username: ENC[AES256_GCM,data:4rCGlAF7N5g=,iv:v/Zb7lioqJOR54eyVSzEHWzEWaP+7wZlq6elPKUGI10=,tag:lwinJ/T/MyUy9D6qEZj3eA==,type:str]
kind: Secret
metadata:
    name: forgejo-admin-creds
    namespace: forgejo
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UGxXdnhVOEJrSHptUkVi
            V25LWEtXcEcrbFRzLzJ3TkdHSngwei9HZkV3Ckpwb01xVnJuU0wwQjkvbHArM1BM
            VTEzVjUzeEFucG1nWDl1cStjZDBPVWsKLS0tIHNncEl1KzVPTHBiWnFEMzZBRUtl
            cnI1SERWSUxmOHFycmFRUHhZaGZjdUkKDqV3B/ofVl0+Aoh3juPYyBgPxpighDwQ
            PvmGu2HLXF13oojgNsowWQdjXUYBcSWbLimhTtwayZvdqFy+dnztpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:17:02Z"
    mac: ENC[AES256_GCM,data:lSAL9X4n6epM6LTQOg9aB1MblKN7BKkBn1FEl7EUv4pCsQJaCwlBxuwcYP/J0+s+MiPZtKjwHi5uXEy4ybEwrW7+PoZhy8RUPA00D3gbattIhXK2WuNwitlI0QMA1KRQut9Utr1diifQosizhE/Sc08jtX+yIrq3uEXGe02jwQQ=,iv:A/ZrespdDQuLAb8jfoQ822Ms5nt03wVqQASIRxKdJvk=,tag:47yCM9Kt5jikz9QKapyr4Q==,type:str]
    version: 3.13.3
