apiVersion: v1
data:
    email: ENC[AES256_GCM,data:ax5MHNunE3IIupWS7eWsWafnIOyUf8I2,iv:RXrjXogPVN03KTKswyiN/tU82rCEBnPum5LB5flX92U=,tag:t5dkR2Uknbg5zZSHssxRhQ==,type:str]
    password: ENC[AES256_GCM,data:qtTrlV5N0v6O3bPhlZC1T89bz6QqnI/m,iv:7HovD8Tv8MXfEz0HZg+H58IFuysay7633tA0Y1sxfNE=,tag:g0QliQV04EdTXKY8L4EXIA==,type:str]
    username: ENC[AES256_GCM,data:2U+KqaDM9+/4mZ8h,iv:JNc/pWdvTNQueLYp9KQWilYUjRRGIyAReusVAerWCu0=,tag:OoYW6FKugKmoefmWreONkw==,type:str]
kind: Secret
metadata:
    name: forgejo-admin-creds
    namespace: forgejo
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T2Z4dHFySzJXNFZqR2xZ
            b1A5Q0RNKzc5ZDVFQnQ3MjF3dWtIbXJTUTI0CmxuU0twRnBLaDBHU3BNMlEvbXRT
            TzJsQkhTL1FPWWg0NURHYWRDeHVWR3cKLS0tIE15bHEzUE1SeGdzNnBuRURBVEhN
            M0lNaTZPN3dzcDdNMzdFU0lEbU13REkKbVLlKBxRQ/DUDHpa+7iB8yBaoPRTPjFt
            CRl7mnf9D+sPBUeQc+Q1WddvIKLKvXwzJpKpMNE2LrT86WOJqR+onw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T01:20:04Z"
    mac: ENC[AES256_GCM,data:cTj0Y9LMHuzkiP2jYb1YwNr2T+Sb5EFKHx5gGcahbRRQXcixyDjTgh1jOjQzihVd6nwAPF2IcV076HAHuF+mnFoygxITFq3LpRQrlz6JJUVzd3oEZ5ImvmR4AAUtctyMzL87HwtnflyZM1ji6S9z81p/rbDz3F5ZY9ul8OeO+Tc=,iv:YazcATM50ygMQKQfH2HQ1bvMz9Jvvxgy6eC0wQsZsGM=,tag:Pg6ijrBWABMrytG0xI8dcg==,type:str]
    version: 3.13.3
