apiVersion: v1
data:
    database: ENC[AES256_GCM,data:CX3RNSIvBi6WjCNX,iv:/wYjvfrBgxMdesSuLng1BHBWMfmjMKI325i2P8WQSQg=,tag:mki18fO0T4Ltzh2nXKJ1hQ==,type:str]
    password: ENC[AES256_GCM,data:McXLNKSwPUInNeXZtEherR2rkTeMBB9tImQKZw==,iv:Un7KRAajaIa9f96pJCtRjModEZ7Kpy91fSsidG0YRww=,tag:u85qKMLMwC62Xuk+6IgJ2g==,type:str]
    username: ENC[AES256_GCM,data:vnNZt4MrP1vNZLg3,iv:GRqTQs7AX3geACGZml5AtPSmiMRpqD0AkmlBsZ8w5SE=,tag:SkUGVdw990TsINgy/8f4Cw==,type:str]
kind: Secret
metadata:
    name: forgejo-postgres-creds
    namespace: forgejo
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYXFsT2M1bFhnc2lqemR3
            OS8vZmhmQ1FqUUdudCs4WGRzdzBDK3JURVU4CnZ6YmxhYy9EcDZqK0ZlZHpqejRo
            c0Z3UFVpdWwvOXZjRzBoMSsyS0JnVEEKLS0tIGpMdEJVMURjZU9pSkNDRDAzbmNB
            NDRIT25IL1dxRUlHTkxPSUY1N2xtckEKY0LZvv0umMuwB3FdUeJ6EJbfy8TPGCAF
            oDoDOh4GK120nM1prYwB1UMvmQllelf+jFMe8aR9gJNvqgtmGVjxSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:04:10Z"
    mac: ENC[AES256_GCM,data:f8VGLWAwhPYSL4Ujn39d0cpXb24wNjoBWeD/AFK0t11e1s/w8nQNN7G4IcyNUTcdLqYsr4yGQ6jO4WTKIElAN9PsqQfQUBZQyWnJ59L5CZ6rfQWpM1EEvCcAtOZaPWSBGFoCb+rcOCnCKqVo7MfGMiVYOWSnddjXVLWx1Nclqxg=,iv:w+eE5di0mdtPtFW6JQNF9qBFP8rWAY0rPmJYNZMCaT8=,tag:BMGvN87OvjOT9+ACc3I9bg==,type:str]
    version: 3.13.3
