apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-creds
    namespace: pgadmin
data:
    password: ENC[AES256_GCM,data:MVOOl94C852PJcf1TE2wzSnl1l8=,iv:9oyN6ZROHSg3kieSEweEq7YTGrxj2o89X0CyIOAJ17Y=,tag:O+diLSXwK+uxMGTxo0W/sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRHExa3Noelp0Yy9oeGhP
            aTNiMDgrWXk4N1FpWjN2L1pYc2xsdzlyS0dVCmJ1UVoycUtsU0NUdEZQalhONlE1
            eVpxL2FOSlZwUFpoV0MvdE4wbE1RQ0EKLS0tIGhmQnNOSVg4T3FvdTVGTFM2bzA4
            N1hKYjNxZmRlL2FNS29BMXJLZE4xTTQK6HpyLTQG5Q+xqG3CUtLv6lSWqchMJtk2
            UN67QqZdzAdw/ftMsQarON1MxHkz80cNFGBD+SKAvGPuLgzbgx9naA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T17:32:37Z"
    mac: ENC[AES256_GCM,data:9RCU98HcfyoXp8DQG+OxQeUAdJ9hgSS1G1gdWBrz7IG6hgM9La7n75VcOj7z3SiEBAQHZtcp9ZwaOMSxpjJZeQN5rKhH6fB7PJFwQsXvOKOl9Q7TDxoFIosVmDzdvHzlJYsH3lcalabbHBXghe+mGm6NoMbmz2TwJTi1/xtX+p8=,iv:XMBMidaXEdkZKezKN/4rhR1qqLmcNYFSJc3VZ/70/4c=,tag:RH1wF25yXRdB5ctUWgxSSw==,type:str]
    version: 3.13.3
