apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
