apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:S6zrTxNBl//UlKHLPc1s9P+xTojF6i3VauJS//I5XMhN0DP2Y7kulPNyQVASR8qKxqqrZdY3Q70=,iv:6BYIn5/nycyhXzTlefnM0jwEfyQjUjatXArcVb1wD5E=,tag:9XXaqHeIAsdE0X2h7/zXNw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReHBaMSt3N1Bta29pV0c2
            dEpGWTVha05hZTQxamhPWWxFTkdvR21qMERZClk4QXJ3UTMyYk9VVDdKZVdzcVY4
            cy9BeDdZS1o1K0wyZGlUOFhrMFpQcWsKLS0tIGd3YUJBYzlEVld2SnNqQkZ3YTJz
            MUdBN0o4Z2lYdDFDai9kc0xLSDk0ck0KkbVJQJOVrmCCEqvVyaaNXVVeym4pp8CA
            X0XIZJnwdgqcvA9cD6Tx1fNlABMYuv0RPSeTvNLyMN0Lu+Qa7Ay5GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r60ahuly9wzej7nrhlaxxqjtqexwl2uekrw9527zaa5svsmea9quadgkq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T01:13:06Z"
    mac: ENC[AES256_GCM,data:1h1/HnYG2dIjOyzX9zBWB5MIv+jpzCDeBRsnymEYjuSO/qZPTwk8vOHnkAtctvVYtF9cgmSR/yB+/Eeo0y5WP6CipGYk4TG/M6qg51cliSEinRMjtE3f3j+PQQnt/swo9QZIiACEQKPwzEeNp8uUtC7BRBul5pKkosGWMOW9CKI=,iv:IbXjWXhRuGJu73ISceyNjQCXjq65gtV61VQ62C380PQ=,tag:0RZ/PMCZRA4zfCUQRurmIw==,type:str]
    version: 3.13.3
